### ISSUE TITLE
Exception after submitting an order 

### ISSUE THREAD

**Issue by BrelKsiba** [tinymanorg/tinyman-py-sdk#14]
I have a loop in which I am checking some conditions. Once these conditions verified, I am submitting an order. 

Very few times where the _submit_ function is called without an error but most of the time I have the following exception. 

 result = client.submit(transaction_group1, wait=True)
  File "D:\Programs\lib\site-packages\tinyman\v1\client.py", line 34, in submit
    raise Exception(json.loads(e.args[0])['message']) from None
  File "D:\Programs\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\Programs\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Programs\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Any idea about the root cause of this non deterministic behavior resulting to this exception? 
Many Thanks

**Comment by fergalwalsh** [comment]
It would be very helpful if you could modify `D:\Programs\lib\site-packages\tinyman\v1\client.py", line 34,` to print `e` and `e.args` so we can understand what is being returned in this case. 
We assumed it was always some JSON but it seems this is not the case.

**Comment by BrelKsiba** [comment]
after print (e) and print (e.args) I get the following: 

TransactionPool.Remember: transaction ETIWFPB5AI3V4XI6VZGTADCQ4ZIUEDTPWA74PK7SVQY3JJOTFUWA: underflow on subtracting 6122893675 from sender amount 522767870
('TransactionPool.Remember: transaction ETIWFPB5AI3V4XI6VZGTADCQ4ZIUEDTPWA74PK7SVQY3JJOTFUWA: underflow on subtracting 6122893675 from sender amount 522767870',)

**Comment by rgpayne** [comment]
i was getting the same error when attempting to initiate a swap while having 0 of an asset. user error in my case

**Comment by fergalwalsh** [comment]
Error handling fixed in a3025d7a9ac33c33d6d7d0e223bba5b1592852c9
