### ISSUE TITLE
Old Algoexplorer API Url causing 50X Bad Gateway Errors

### ISSUE THREAD

**Issue by Flying-Bison-Appa** [tinymanorg/tinyman-py-sdk#16]
Hey,

I'm getting frequent and inconsistent 500 Bad Gateway Errors from fetch_asset, fetch_pool, etc calls. Looking at tinyman/v1/client.py I noticed the AlgoExplorer API Link referenced seems to be the old API. Based on their developer docs: https://algoexplorer.io/api-dev/v2 the new URL is https://algoexplorerapi.io (Current used in file is https://api.algoexplorer.io). I tried changing that value in a local copy of this module and it started working consistently. I believe a similar shift is also needed for the testnet client as well.

**Comment by aleve99** [comment]
Yes also all internal functions use the algod client and not possibilty to swap to the indexer. As algoexploer is dismissing the algod apis should be changed something. Indexer returns the response inside a key, like {'accounts': ...}
