### ISSUE TITLE
How to check asset amount in wallet?

### ISSUE THREAD

**Issue by majestique** [tinymanorg/tinyman-py-sdk#22]
thinking i may have to use algod for this? i want to keep purchasing an asset until I spend all ALGO, I don't want to purchase it all at once because slippage will be too high

**Comment by efe** [comment]
You can use `account_info` in `py-algorand-sdk`. https://py-algorand-sdk.readthedocs.io/en/latest/algosdk/algod.html#algosdk.algod.AlgodClient.account_info

BTW, `Wallet` does not have asset or algo. `Account` has.

**Comment by ctubio** [comment]
:gift: 
```python
def get_wallet_asset(asset, fetch=True):
  global WALLET
  if (fetch):
    WALLET = client.algod.account_info(client.user_address)
  try:
    return asset((next(
      item for item in WALLET['assets'] if item['asset-id'] == asset.id
    ) if asset.id else WALLET)['amount'])
  except:
    return asset(0)

```

**Comment by gokselcoban** [comment]
Thank you for the question and answers. The issue looks like resolved.

I will close this issue, feel free to reopen it.
