### ISSUE TITLE
ASA with Unicode character 🪙 in unit-name raises KeyError in pools.py

### ISSUE THREAD

**Issue by ipaleka** [tinymanorg/tinyman-py-sdk#24]
```
pool = {
...
    liquidity_asset_name': liquidity_asset['params']['name']
...
```

A workaround for us is just a simple `liquidity_asset['params'].get('name')`, but you'd probably want a solution/name that includes the other ASA in the pool.

**Comment by fergalwalsh** [comment]
Can you explain why you need this?
The `name` of the liquidity asset is enforced by the contracts so a liquidity asset without a name should be an impossibility.

**Comment by ipaleka** [comment]
I have to admit that the code we use is a few months old and we have used it to check is there a liquidity pool created for a given pair of ASA.

Is there some better method for us to retrieve such information?

**Comment by fergalwalsh** [comment]
Ah I see. It would still be odd if this was the first line to raise an error in that case though. 

If a pool exists then `pool.exist` is True, else None
e.g
```
pool = client.fetch_pool(5, 0)
pool.exists == None

pool = client.fetch_pool(31566704, 0)
pool.exists == True
```

> Is there some better method for us to retrieve such information?
Another way is to use Tinyman's analytics APIs to retrieve a list of pools or to follow the chain for pool creations and verify their integrity by comparing addresses using this SDK. That's what the analytics backend does.

**Comment by ipaleka** [comment]
> Ah I see. It would still be odd if this was the first line to raise an error in that case though.

This is our original code:
```
    asset1 = tinyman_client.fetch_asset(asset1_id)
    asset2 = tinyman_client.fetch_asset(asset2_id)
    pool = tinyman_client.fetch_pool(asset1, asset2)

    if not pool.exists:
```
And it raises KeyError on the third line above.

> Another way is to use Tinyman's analytics APIs to retrieve a list of pools or to follow the chain for pool creations and verify their integrity by comparing addresses using this SDK. That's what the analytics backend does.

I think we'd rather stick to "Simple is better than complex." and "Easier to ask for forgiveness than permission.". :)

```
try:
    pool = tinyman_client.fetch_pool(asset1, asset2)
except KeyError:
    #...  
```

**Comment by ipaleka** [comment]
**Sorry**, the title is misleading, it's not an empty unit name, it's the Unicode character in the unit name that causes this:

https://algoexplorer.io/tx/QJGZVVSTOTAISJFU5VC73GPBEJ566LUQWRQAQEREYT7KPSP5HOIQ

**Comment by ipaleka** [comment]
```
>>> pool = client.fetch_pool(403996358, 0)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/ipaleka/dev/venvs/asa/lib/python3.9/site-packages/tinyman/v1/client.py", line 20, in fetch_pool
    return Pool(self, asset1, asset2, fetch=fetch)
  File "/home/ipaleka/dev/venvs/asa/lib/python3.9/site-packages/tinyman/v1/pools.py", line 142, in __init__
    asset_a = client.fetch_asset(asset_a)
  File "/home/ipaleka/dev/venvs/asa/lib/python3.9/site-packages/tinyman/v1/client.py", line 25, in fetch_asset
    asset.fetch(self.algod)
  File "/home/ipaleka/dev/venvs/asa/lib/python3.9/site-packages/tinyman/assets.py", line 27, in fetch
    self.unit_name = params['unit-name']
KeyError: 'unit-name'
```

**Comment by anantasty** [comment]
The actual issue seems to be in algod.asset_info not being able to parse unicode.

**Comment by gokselcoban** [comment]
I couldn't reproduce the issue with the latest versions of Tinyman and Algo SDK. Looks like the issue is resolved. Thank you for reporting it.
