### ISSUE TITLE
wait for confirmation could run into infinite loop

### ISSUE THREAD

**Issue by BrelKsiba** [tinymanorg/tinyman-py-sdk#26]
It could happen that the function wait_for_confirmation(client, txid) is running/waiting undefinitely. This happens some times for a reason that I cannot explain.

Do you know in which case this situation can happen?

A suggestion could be to define the wait_for_confirmation and submit functions with an additional timeout parameter, for example:

def wait_for_confirmation(client, txid, timeout)
 
and/or

def submit(transaction_group, wait, timeout): ---> when wait = True, a timeout could be given.

**Comment by cobang** [comment]
Hi @BrelKsiba,

`wait_for_confirmation` is added to `py-algorand-sdk` too ([see](https://github.com/algorand/py-algorand-sdk/blob/2ef7d3312b6a2bd7bcb2dc430668060ae8ed80d8/algosdk/future/transaction.py#L3014)). It has the feature you have requested with a default value of 1000 blocks which is the maximum range (first valid - last valid). So you can start to use it think.

I think it can be removed from the `tinyman-py-sdk`, or keep it an alias.

**Comment by cobang** [comment]
> Do you know in which case this situation can happen?

Probably it happens if your transaction is not approved by the protocol.
For example, if the price changes more than the given slippage, your transaction fails.

**Comment by BrelKsiba** [comment]
Thx.
Using wait_for_confirmation from py-algorand-sdk fixed the problem. Still need to modify the submit function in Tinyman SDK to add a third parametr for wait_rounds.
