### ISSUE TITLE
v1.0 Pools appear irretrievable 

### ISSUE THREAD

**Issue by jmrMOONBOI** [tinymanorg/tinyman-py-sdk#33]
Minimum code to reproduce:

```
from tinyman.v1.client import TinymanClient
from algosdk.v2client.algod import AlgodClient

algod = AlgodClient('', 'https://api.algoexplorer.io', headers={'User-Agent': 'algosdk'})

# V1 client
client_v1 = TinymanClient(algod_client=algod, validator_app_id=350338509)
# V1.1 client
client_v2 = TinymanClient(algod_client=algod, validator_app_id=552635992)

# Get two assets
YLDY = client_v1.fetch_asset(226701642)
ALGO = client_v1.fetch_asset(0)

# Find pool (which definitely still exists)
# Actual target address is 
# Y74RXNAUAZT2U5PD57Y22NVU6UPW5WNLRLHA763EE5IJSLSJXRAX6YY4OE
pool = client_v1.fetch_pool(YLDY, ALGO)
pool.address # FNWKQUJCBFEW3OIUFAV5WD5WF6YZ52DKCVVCVTW5G53TOY5RS4AX57SFXU

# Actual target address is 
# KX6S647W6BEN6XHEJVMXK3UYLVNGT2Q6PHQSF5AA2JSSDFSOX7R4MESXRY
pool2 = client_v2.fetch_pool(YLDY, ALGO)
pool2.address # KX6S647W6BEN6XHEJVMXK3UYLVNGT2Q6PHQSF5AA2JSSDFSOX7R4MESXRY
```

**Comment by jmrMOONBOI** [comment]
I've issued a pull request that resolves this here:

https://github.com/tinymanorg/tinyman-py-sdk/pull/34/commits

**Comment by gokselcoban** [comment]
I think SDK doesn't support the old version on purpose. Why do you want to use v1.0?

You can use the old version of the SDK for v1.0.
Ex. `git+https://github.com/tinymanorg/tinyman-py-sdk.git@8eb969d741523aeb33325d2ad0ea33734176b84e`

Doesn't it solve your needs?

**Comment by jmrMOONBOI** [comment]
> I think SDK doesn't support the old version on purpose. Why do you want to use v1.0?
> 
> You can use the old version of the SDK for v1.0. Ex. `git+https://github.com/tinymanorg/tinyman-py-sdk.git@8eb969d741523aeb33325d2ad0ea33734176b84e`
> 
> Doesn't it solve your needs?

There are many reasons a user may want to get old pool addresses. Yes, dowloading an old version of the SDK would allow a user to retrieve old pool addresses correctly, at the expense of being able to retrieve current pool addresses correctly. The fact that the client functions allow you to pass a validator address tells you that this is not intended behavior. 

My pull request resolves the issue. I'm not sure if the Tinyman team cares to merge the request, but if they do not, users should be able to download my pull request directly if they need pool addresses from both v1.0 and v1.1 contracts.

**Comment by gokselcoban** [comment]
Thank you. As you suggested, users can use [your PR](https://github.com/tinymanorg/tinyman-py-sdk/issues/33).
