### ISSUE TITLE
Compatibility issue with py-algorand-sdk 2.0.0

### ISSUE THREAD

**Issue by ipaleka** [tinymanorg/tinyman-py-sdk#55]
https://github.com/algorand/py-algorand-sdk/releases/tag/v2.0.0

All the code from the `algosdk.future` package is moved directly under `algosdk`.

So, for example

`from algosdk.future.transaction import LogicSigAccount`

becomes

`from algosdk.transaction import LogicSigAccount`

`

**Comment by gokselcoban** [comment]
Thank you for informing us about this change.

There is an open PR https://github.com/tinymanorg/tinyman-py-sdk/pull/58 related to this issue.

This will be fixed with the upcoming release.

**Comment by gokselcoban** [comment]
Added `py-algorand-sdk==2.0.0` support 🎉 .

https://github.com/tinymanorg/tinyman-py-sdk/releases/tag/v2.1.1
